### PR TITLE
Add sequence with settings to structure dump

### PR DESCRIPTION
**Pull request by jlahtinen**
Add min and max values, order and cycle flags.

These are sometimes needed when sequence is not solely used for id generation for example.

order flag is quite useful also sometimes for id generation.

### CODE REVIEW

**Comment by yahonda** [comment]
Thanks for opening a pull request. Do you think you need `CACHE_SIZE` to set the cache size of the sequence?

**Comment by jlahtinen** [comment]
@yahonda I think we do not need it. It would be no harm anyway.

**Comment by yahonda** [comment]
Thanks for the answer. This pull request has been merged.

**Comment by jlahtinen** [comment]
@yahonda  thank you for keeping this project alive. When you make a new release? Is there any policy for that to read?

**Comment by yahonda** [comment]
This is a new feature then it will be available for 1.9.0 to support Rails 5.2. Not for Rails 5.1 or lower version.
Since it changes the output of the schema dump file, this kind of change is not suitable for the maintenance release.

**Pull request merged**
