### PR TITLE
create_table_definition and add_column take keyword arguments

### PR DESCRIPTION
**Pull request by koic**
Follow up of https://github.com/rails/rails/commit/d700456cb72bd38dcf6f540a3b7f6593879b456f, https://github.com/rails/rails/commit/e02b3d1b0ede87396122f90d773b9030ce9d469e, and https://github.com/rails/rails/commit/70afbf245f1038b91a664dcee98cb8dea61d9b91

### CODE REVIEW

**Comment by koic** [comment]
The master branch failed as reported by #1943. This failure is based on it.

**Comment by yahonda** [comment]
@koic Would you rebase this pull request based on the current master? 

Some of failures reported at #1943 have been fixed by https://github.com/rails/rails/pull/37646 . Then remaining two failures are isolated.

**Comment by koic** [comment]
@yahonda Thanks for the fixing. I rebased this PR.

**Comment by yahonda** [comment]
No regressions found for this pull request.

**Pull request merged**
