### PR TITLE
Rails 7.x Compatibility

### PR DESCRIPTION
**Pull request by hss-mateus**
Related to #2357 

This PR just applies all the patches provided by @andynu since now, plus some temporary workarounds to get it working with a simple model.

I have tested this branch on a Rails 7.2.0.beta2 application, and it seems to be working for simple queries/models.

### CODE REVIEW

**Review by yahonda — COMMENTED** [review]
Please ignore my previous update.

**Comment by yahonda** [comment]
Thanks for your contribution. Let me merge this pull request and address some TODO/known issues.

**Comment by akostadinov** [comment]
Hi, this PR forces the old visitor (`Oracle` instead of `Oracle12`) and this is a breaking change. Why shouldn't we force the new visitor instead? And also no documented way to select the desired visitor. Did nobody else get unexpected results with this version?

cc @yahonda

**Comment by andynu** [comment]
@akostadinov Rails 7.x is out of main support. And security support for 7.2 ends in 3 months. I highly encourage you to upgrade.

https://endoflife.date/rails

**Comment by akostadinov** [comment]
@andynu this change remains active in master:
https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L353-L360

It seems to have been done as a temporary hack and remained. Or do you intentionally want to keep this hardcoded to the Oracle 11 visitor?

P.S. Very recently my changes were refused, I assume because they don't apply to Oracle 11 which is EOL since longer. So I respectfully don't appreciate the EOL sentiment in the post. (let me use the opportunity to point out that Oracle11 carries such a technical depth and obviously creates real confusing issues, that I don't understand why should we actively keep it supported as a higher tier than mainstream versions)

**Comment by andynu** [comment]
Fair point if the behavior you describe is still on master. Commenting on a 2 year old pull request is confusing from my end. If you would like to submit an issue with a specific demonstration of the "unexpected results" I'd be happy to continue the discussion there.

**Comment by akostadinov** [comment]
FYI this is supposedly fixed with https://github.com/rsim/oracle-enhanced/pull/2573, thanks to yahonda, who beat me to it and fixed it in a better way to what I started to do.

P.S. commenting on the source of the issue to potentially notify the original authors and for a reference whenever somebody hits it. Like I find it useful for myself when I see additional context in old issues/PRs/threads. So I assume might be useful to others. Regards.

**Pull request merged**
