### PR TITLE
Release18

### PR DESCRIPTION
**Pull request by mimiyanwk**
I have fixed unexpected behavior when using bind params for CHAR column #1680
grafik

### CODE REVIEW

**Comment by yahonda** [comment]
Thanks for opening a pull request.  
I was not aware that you have attached some screenshots in the description. Unfortunately, I would say it is not a valid pull request. Unable to merge, at least.

* Open a pull request with the actual source code, not screenshots of GitLab
* Open a pull request to `master` branch, not for `release18` or other `release*` branches

Let me close this one.

Thanks.

**Comment by mimiyanwk** [comment]
I don't know how can I create a pull request to master.

**Comment by mimiyanwk** [comment]
I got a error message:
is it a permission problem?
$ git push origin fix-char-column
fatal: HttpRequestException encountered.
   Fehler beim Senden der Anforderung.
Username for 'https://github.com': mimiyanwk
remote: Permission to rsim/oracle-enhanced.git denied to mimiyanwk.
fatal: unable to access 'https://github.com/rsim/oracle-enhanced.git/': The requested URL returned error: 403

**Comment by yahonda** [comment]
I'd suggest you follow this instruction "Creating a pull request from a fork" 
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Also please validate your `origin` points your forked repository `git@github.com:mimiyanwk/oracle-enhanced.git`, not `git@github.com:rsim/oracle-enhanced.git`

**Pull request closed without merging**
