### PR TITLE
Fix cursor leak when using activerecord-import gem

### PR DESCRIPTION
**Pull request by solerman**
Not sure how to test this, but seems to fix my use of activerecord-import over jruby

### CODE REVIEW

**Comment by yahonda** [comment]
Thanks for opening a pull request. 

I understand it may be difficult to create a test case but to merge this fix into master, some test cases are necessary.
Also, would you confirm and provide this information?


* How do you find there was "cursor leak"?
If you saw `ORA-01000: maximum open cursors exceeded` error please check Rails `:statement_limit` is lower than Oracle database `open_cursors` described [here](https://github.com/rsim/oracle-enhanced/blob/master/README.md#upgrade-rails-50-or-older-version-to-rails-51)

* Please describe how did you reproduce this "cursor leak"
- Rails version
- Oracle enhanced adapter version
- JRuby version
- Oracle database version
- `activerecord-import` gem version
- Steps to reproduce

Thanks.

**Comment by solerman** [comment]
-  How do you find there was "cursor leak": The configured server used 10K as cursor limit. Using PL/SQL developer, lots of cursors with an insert are left open until ORA-01000 is thrown.

- Rails version: I'm not using rails, just activerecord 5.1.2 (It also happens on 4.2.5)
- JRuby version: 9.1.12 (It also happens on 7.1.26)
- Oracle database version: 11.2.0.4
- activerecord-import gem version: 0.19.1

- Steps to reproduce: the gem adds to each model an import method which you can call with an array of hashes where each hash key matches the model's attributes. Calling it at lot of data should trigger the issue.

**Comment by yahonda** [comment]
Thanks for the update. I think I am able to reproduce it.

* Ruby version
```
$ ruby -v
jruby 9.1.12.0 (2.3.3) 2017-06-15 33c6439 OpenJDK 64-Bit Server VM 25.141-b16 on 1.8.0_141-b16 +jit [linux-x86_64]
```

* Steps to reproduce
```ruby
$ more rep_current.rb
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", "~> 5.1.0"
  gem "activerecord-oracle_enhanced-adapter", "~> 1.8.0"
  gem "activerecord-import"
  gem "minitest"

  platforms :ruby do
    gem "ruby-oci8"
    gem "byebug"
  end
end

require "active_record"
require "minitest/autorun"
require "logger"
require "active_record/connection_adapters/oracle_enhanced_adapter"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# Set Oracle enhanced adapter specific connection parameters
DATABASE_NAME = ENV["DATABASE_NAME"] || "orcl"
DATABASE_HOST = ENV["DATABASE_HOST"]
DATABASE_PORT = ENV["DATABASE_PORT"]
DATABASE_USER = ENV["DATABASE_USER"] || "oracle_enhanced"
DATABASE_PASSWORD = ENV["DATABASE_PASSWORD"] || "oracle_enhanced"
DATABASE_SYS_PASSWORD = ENV["DATABASE_SYS_PASSWORD"] || "admin"

CONNECTION_PARAMS = {
  adapter: "oracle_enhanced",
  database: DATABASE_NAME,
  host: DATABASE_HOST,
  port: DATABASE_PORT,
  username: DATABASE_USER,
  password: DATABASE_PASSWORD
}

ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)

#ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true do |t|
    t.string    :name
    t.timestamps
  end
end

class Book < ActiveRecord::Base
end

class BugTest < Minitest::Test

  def test_insert_10_000_rows_using_activerecord_import
    books = []
    10000.times do |i|
      books << Book.new(:name => "emp_#{i}")
    end
    Book.import books
    assert_equal 10000, Book.count
  ensure
    Book.delete_all
  end
end
```

* Result
```ruby
$ ruby rep_current.rb
The dependency ruby-oci8 (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for java but the dependency is only for ruby. To add those platforms to the bundle, run `bundle lock --add-platform ruby`.
The dependency byebug (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for java but the dependency is only for ruby. To add those platforms to the bundle, run `bundle lock --add-platform ruby`.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies.......
Using rake 12.0.0
Using concurrent-ruby 1.0.5 (java)
Using i18n 0.8.6
Using minitest 5.10.3
Using thread_safe 0.3.6 (java)
Using builder 3.2.3
Using erubi 1.6.1
Using nokogiri 1.8.0 (java)
Using rack 2.0.3
Using nio4r 2.1.0 (java)
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 8.0.0
Using ruby-plsql 0.6.0
Using bundler 1.15.3
Using method_source 0.8.2
Using thor 0.19.4
Using tzinfo 1.2.3
Using loofah 2.0.3
Using rack-test 0.6.3
Using sprockets 3.7.1
Using websocket-driver 0.6.5 (java)
Using mime-types 3.1
Using activesupport 5.1.3
Using rails-html-sanitizer 1.0.3
Using mail 2.6.6
Using rails-dom-testing 2.0.3
Using globalid 0.4.0
Using activemodel 5.1.3
Using actionview 5.1.3
Using activejob 5.1.3
Using activerecord 5.1.3
Using actionpack 5.1.3
Using activerecord-import 0.19.1
Using activerecord-oracle_enhanced-adapter 1.8.1
Using actioncable 5.1.3
Using actionmailer 5.1.3
Using railties 5.1.3
Using sprockets-rails 3.2.0
Using rails 5.1.3
-- create_table(:books, {:force=>true})
   -> 1.3962s
Run options: --seed 5290

# Running:

E

Error:
BugTest#test_insert_10_000_rows_using_activerecord_import:
ActiveRecord::StatementInvalid: Java::JavaSql::SQLException: ORA-01000: maximum open cursors exceeded
: DELETE FROM "BOOKS"



bin/rails test rep_current.rb:64



Finished in 7.576959s, 0.1320 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

**Comment by yahonda** [comment]
The test case above does not reproduce after cherry-picking the commit into release18 branch.
```ruby
  gem "activerecord-oracle_enhanced-adapter", github: "yahonda/oracle-enhanced", branch: "release18_cherry_pick_1409"
```

**Comment by solerman** [comment]
A way to check open cursors count without blowing up the database:

select a.value, s.username, s.sid
from v$sesstat a, v$statname b, v$session s
where a.statistic# = b.statistic#  and s.sid=a.sid
and b.name = 'opened cursors current' and a.value > 0;

**Comment by yahonda** [comment]
Merged this pull request. 

I do not add test cases to Oracle enhanced adapter since I prefer not to let Oracle enhanced adapter test cases depending on another 3rd party ActiveRecord related gem.  This is an exceptional case. Usually, pull requests need necessary test cases included.

Thanks.

**Pull request merged**
