### PR TITLE
Define adapter type maps statically when possible

### PR DESCRIPTION
**Pull request by yahonda**
This pull request supports  `Define adapter type maps statically when possible` https://github.com/rails/rails/pull/42773 in Active Record Oracle enhanced adapter. 

Also, to make CI green this pull request needs these additional commits.
* Use Oracle Instant Client 21.4
* Rename `_quote` to `quote`
* Rename `_type_cast` to `type_cast`

### CODE REVIEW

**Comment by yahonda** [comment]
https://github.com/rails/rails/commit/c5bf2b4736f2ddafbc477af5b9478dd7143e5466 support is necessary.

**Comment by yahonda** [comment]
Now CI is green. Let me squash commits and make this pull request 'Ready for review.'

**Comment by yahonda** [comment]
@koic Would you review this pull request? The main differences from the previous commits are:
https://github.com/rsim/oracle-enhanced/pull/2199/files#diff-0d21136da5aee9b25213dcf874f62418fa24a06a90237e069642a5af54e7b2efR727

https://github.com/rsim/oracle-enhanced/pull/2199/files#diff-0d21136da5aee9b25213dcf874f62418fa24a06a90237e069642a5af54e7b2efR729-R731

**Review by koic — APPROVED** [review]
Looks good to me. Thanks for tackling this!

**Comment by yahonda** [comment]
Thanks for the review. It gets merged.

**Pull request merged**
