### PR TITLE
Enable performance unfreeze string cop

### PR DESCRIPTION
**Pull request by yahonda**
This pull request enables performance `Performance/UnfreezeString` cop. 
It will be merged if https://github.com/rails/rails/pull/32971/ is merged to Rails.

As this cop does not support autocorrect, I'd like to prepare this pull request in advance.

@koic Would you review this pull request and have some comments. Do not merge it yet.

### CODE REVIEW

**Comment by koic** [comment]
This looks good!

By the way, unfortunately I’m not sure why `Performance/UnfreezeString` cop doesn't support autocorrect. Let's ask @pocke at RubyKaigi 2018. Thank you.
bbatsov/rubocop#4586

**Comment by yahonda** [comment]
Thanks for the review. I'm attending RubyKaigi also, please let me join the discussion.

**Comment by koic** [comment]
Sure, pleasure. I'm looking forward to meeting you.

**Comment by yahonda** [comment]
https://github.com/rails/rails/pull/32971 has been merged to Rails.

**Pull request merged**
