### PR TITLE
Support connection strings in DATABASE_URL

### PR DESCRIPTION
**Pull request by jbotelho2-bb**
We are trying to move our Rails apps to stick to using environment variables for configuration, and noticed that we could not put a connection string in the url.

To solve this, I added a simple addition to support putting a connection-string in the URL (as the path), when the host is `connection-string`. This change seemed fairly simple and unlikely to break existing configurations, but I'm open to other ways to pick up on the connection string from there.

### CODE REVIEW

**Comment by yahonda** [comment]
Thanks for opening a pull request. would you add specs to validate the `DATABASE_URL=oracle-enhanced://user:secret@connection-string/(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=xe)))` works for both OCI and JDBC connections.

Thanks.

**Comment by jbotelho2-bb** [comment]
I added JRuby/JDBC support and a spec to cover both platforms (OCI and JDBC).

**Comment by yahonda** [comment]
Thanks.

**Comment by jbotelho2-bb** [comment]
@yahonda thanks for merging this.

Would it be possible to get this change into the 1.6 release as well? Should I make a pull request for that?

**Comment by yahonda** [comment]
#1036 has been merged to release16 branch.

**Pull request merged**
