### PR TITLE
fix Handling with char-column problem

### PR DESCRIPTION
**Pull request by mimiyanwk**
the problem with processing with char column is fixed

### CODE REVIEW

**Comment by yahonda** [comment]
Thanks for opening a pull request. Would you add some test cases? As far as I remember there was a test case explained in #1680. Thank you.

**Comment by yahonda** [comment]
Thanks for updating specs. Would you address RuboCop offenses reported at https://codeclimate.com/github/rsim/oracle-enhanced/pull/1760 ?

**Comment by mimiyanwk** [comment]
I have added a test case explained in #1680 but have a question:
Char was mapped to String in ruby-oci8.
How can I check if a String type of result set is from Char in oci_connection.rb?

**Comment by mimiyanwk** [comment]
The test case explained in #1680 is now completely implemented.

**Comment by yahonda** [comment]
Thanks. Would you squash commits into one?

**Comment by mimiyanwk** [comment]
Squashing commits into one was finisched.

**Comment by yahonda** [comment]
Thank you.

**Pull request merged**
