### PR TITLE
Update README for 7.0 [skip ci]

### PR DESCRIPTION
**Pull request by yahonda**

### CODE REVIEW

**Comment by yahonda** [comment]
Let's merge this pull request when Rails 7.0.0 and Oracle enhanced adapter 7.0.0 are released.

**Comment by koic** [comment]
Can you update the following text in the README.md?

```diff
-Oracle enhanced adapter can be used from Ruby on Rails versions between 2.3.x and 6.1 
+Oracle enhanced adapter can be used from Ruby on Rails versions between 2.3.x and 7.0
```

**Comment by yahonda** [comment]
Rails 7.0.0 has been released https://rubyonrails.org/2021/12/15/Rails-7-fulfilling-a-vision .

**Comment by yahonda** [comment]
Let me merge this pull request first. Oracle enhanced adapter v7.0.0 is coming.

**Pull request merged**
