### PR TITLE
Backport #1962 to release52 branch

### PR DESCRIPTION
**Pull request by yahonda**
Updated manually because there is a git conflict to backport #1962 to release52.

### CODE REVIEW

**Comment by koic** [comment]
release50 branch in the title seems to be typo. It will be release52 branch correctly. This is a nitpick.

**Comment by yahonda** [comment]
Addressed the incorrect branch name. Thanks for the review.

**Comment by koic** [comment]
Thanks!

**Comment by yahonda** [comment]
FYI. My development environment is being migrated then it may take another couple of days to release the newer version of Oracle enhanced adapter 5.2.7.

**Pull request merged**
