### PR TITLE
[WIP] Migrate Arel code from Rails to Oracle enhanced adapter

### PR DESCRIPTION
**Pull request by yahonda**
This is a draft pull request to support https://github.com/rails/rails/pull/38946 

### Required
- [ ] Migrate Arel library code to make CI green
- [ ] Migrate git commit history

### Optional
- [ ] Migrate test code
because the unit test for Arel is written in Minitest, Oracle enhanced adapter uses RSpec. Arel has been a private API at Rails then it may be fine without tests for the time being.

### CODE REVIEW

**Comment by yahonda** [comment]
@koic I'd like to get your help how to migrate Arel library code with git commit history. I think you have done a similar job at https://github.com/rubocop-hq/rubocop/issues/5977#issuecomment-429235642

**Comment by koic** [comment]
Yeah, I will try this one.

**Comment by koic** [comment]
I created the following branch to solve this.
https://github.com/koic/oracle-enhanced/tree/merge_arel_visitors

It passes specs using `remove_unused_visitors` branch of  kamipo/rails repository.

```ruby
gem "activerecord",   github: "kamipo/rails", branch: "remove_unused_visitors"
```

You can cherry-pick these commits into this PR or I can open a new PR If you'd like.
https://github.com/koic/oracle-enhanced/compare/master...merge_arel_visitors

**Comment by yahonda** [comment]
@koic Thanks for the great work! Would you open a new pull request?

**Comment by koic** [comment]
I opened PR #2002. Thank you.

**Comment by yahonda** [comment]
Closing this draft pull request.

**Pull request closed without merging**
