### PR TITLE
Avoid extra `BindParam` allocation to generate placeholder in queries

### PR DESCRIPTION
**Pull request by koic**
Resolves https://github.com/rsim/oracle-enhanced/issues/2152 and follow https://github.com/rails/rails/pull/41577.

The tests that fail below have not yet been resolved.
https://github.com/rails/rails/commit/6ee96a8f42d6b13bffd46342248f447d9f289288.

### CODE REVIEW

**Comment by yahonda** [comment]
`ORA-01722: invalid number` error occurred at this statement, likely at `INTO :returning_id`.

```
ActiveRecord::InternalMetadata Create (19506.5ms)  INSERT INTO "AR_INTERNAL_METADATA" ("KEY", "VALUE", "CREATED_AT", "UPDATED_AT") VALUES (:a1, :a2, :a3, :a4) RETURNING "KEY" INTO :returning_id  [["key", "environment"], ["value", "default_env"], ["created_at", "2021-03-29 12:47:19.056199"], ["updated_at", "2021-03-29 12:47:19.056199"], ["returning_id", nil]]
```

Compared to this statement with that of Oracle enhanced adapter release61 branch, it does not have `INTO :returning_id`.

```
ctiveRecord::InternalMetadata Create (6.8ms) INSERT INTO "AR_INTERNAL_METADATA" ("KEY", "VALUE", "CREATED_AT", "UPDATED_AT") VALUES (:a1, :a2, :a3, :a4) [["key", "environment"], ["value", "default_env"], ["created_at", "2021-03-29 23:06:55.059484"], ["updated_at", "2021-03-29 23:06:55.059484"]]
```

Then just calling super at `sql_for_insert` method workarounds ORA-1722 error.

```
$ git diff 4f03593176b220f48e565bdf4df13e439f821e64...b19e8f4022768541605628bf376164ed1ccd4f78
diff --git a/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb b/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
index 54144633..814c6b9b 100644
--- a/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
+++ b/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
@@ -79,10 +79,6 @@ module ActiveRecord
         # New method in ActiveRecord 3.1
         # Will add RETURNING clause in case of trigger generated primary keys
         def sql_for_insert(sql, pk, binds)
-          unless pk == false || pk.nil? || pk.is_a?(Array)
-            sql = "#{sql} RETURNING #{quote_column_name(pk)} INTO :returning_id"
-            (binds = binds.dup) << ActiveRecord::Relation::QueryAttribute.new("returning_id", nil, Type::OracleEnhanced::Integer.new)
-          end
           super
         end

$

**Comment by yahonda** [comment]
Would you add this change?  then CI should be green.

```ruby
$ git diff
diff --git a/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb b/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
index 54144633..631dcffa 100644
--- a/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
+++ b/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb
@@ -79,7 +79,7 @@ module ActiveRecord
         # New method in ActiveRecord 3.1
         # Will add RETURNING clause in case of trigger generated primary keys
         def sql_for_insert(sql, pk, binds)
-          unless pk == false || pk.nil? || pk.is_a?(Array)
+          unless pk == false || pk.nil? || pk.is_a?(Array) || pk.is_a?(String)
             sql = "#{sql} RETURNING #{quote_column_name(pk)} INTO :returning_id"
             (binds = binds.dup) << ActiveRecord::Relation::QueryAttribute.new("returning_id", nil, Type::OracleEnhanced::Integer.new)
           end
$
```

**Comment by koic** [comment]
@yahonda Awesome! Thank you for your investigation and resolution. I have updated this PR.

**Comment by yahonda** [comment]
Failure against Oracle database 11g at https://travis-ci.com/github/rsim/oracle-enhanced/jobs/494935830 will be taken care of by another pull request.

**Comment by yahonda** [comment]
I meant to say I'm going to merge this pull request when CI runs successfully against Oracle Database 18c at GitHub Actions.

**Comment by yahonda** [comment]
Bug report templates failures are expected since it has not merged to master yet.

**Comment by yahonda** [comment]
Thanks for addressing the showstopper.

**Comment by koic** [comment]
Thank you too!

**Pull request merged**
