### PR TITLE
Rename `OracleEnhanced::Connection#select_value` to `_select_value`

### PR DESCRIPTION
**Pull request by yahonda**
Rename `OracleEnhanced::Connection#select_value` to `_select_value` and `OracleEnhanced::Connection#select_one` to `_select_one`
and make them private to avoid other methods all them.

Since #1560 they are only called from `OracleEnhanced::Connection#describe`

Usually `ActiveRecord::ConnectionAdapters::DatabaseStatements#select_value`
and `ActiveRecord::ConnectionAdapters::DatabaseStatements#select_one` should be used.

`OracleEnhanced::Connection#describe` is planned to refactor in the next
major version of Oracle enhanced adapter, likely 6.0 or later.

### CODE REVIEW

**Comment by yahonda** [comment]
@koic Would you provide some comments and reviews for this pull request?

**Comment by yahonda** [comment]
Background for this pull request is also explained in #1560 #1559 #1558 .

**Comment by koic** [comment]
I don't have any problems to worry about this change and background PRs. Is there anything you care about this change?

**Comment by yahonda** [comment]
Thanks for the review. 

The reason why I asked a review was adding a _ to each method was an appropriate way to handle this. 
I was thinking about adding a deprecated warning for these two methods but I prefer these methods will not be executed by adding _ . I should have mentioned this. Will include the reason for future review requests.

Thanks.

**Comment by koic** [comment]
I got it. This looks good. Thanks!

**Pull request merged**
