### PR TITLE
Update dirty.rb

### PR DESCRIPTION
**Pull request by jadon1979**
Fix issue with _field_changed? "wrong number of args 2..3" error that keeps popping up.

### CODE REVIEW

**Comment by yahonda** [comment]
Thanks for opening a pull request. would you update which version of ActiveRecord you are using.

**Comment by jadon1979** [comment]
activerecord (4.2.4)

**Comment by yahonda** [comment]
Thanks for the update. I have checked the method signature of parent method in ActiveRecord 4.2.4. which has not changed.

https://github.com/rails/rails/blob/v4.2.4/activerecord/lib/active_record/attribute_methods/dirty.rb#L141-L143

```ruby
      def _field_changed?(attr, old_value)
        @attributes[attr].changed_from?(old_value)
      end
```

Would you provide a test case to reproduce "wrong number of args 2..3" error.
Thanks.

**Comment by jadon1979** [comment]
As soon as I updated to 1.5 any record.update & create would throw the error in both console and in app.  I don't have the time right now to provide more than that.  I can update this later.

**Comment by yahonda** [comment]
Oracle enhanced adapter 1.5.x does not support ActiveRecord 4.2. Then would you confirm that you are using Oracle enhanced adapter 1.6.3.

```ruby
gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
```
Still you can reproduce this error by using Oracle enhanced adapter 1.6.3 please update the test case to reproduce.

**Comment by jadon1979** [comment]
That worked.  Thanks.  Closing this now.

**Comment by yahonda** [comment]
Thanks.

**Pull request closed without merging**
