### PR TITLE
Rails42 GHI545

### PR DESCRIPTION
**Pull request by apeiros**
Fixes https://github.com/rsim/oracle-enhanced/issues/545

### CODE REVIEW

**Comment by yahonda** [comment]
Thanks for the pull request. 

At first would you remove duplicate commits https://github.com/swisslife-select/oracle-enhanced/commit/232ec82676e7fca5d03b3246e5235cef74adb87c and https://github.com/swisslife-select/oracle-enhanced/commit/c2cde1ba73a4160b21971bb4d8d6d6e97ba71d3c from this pull request since they are already merged to rails42 branch in #550.

If duplicate commits exist it is unclear which pull request addresses which issues.

**Comment by apeiros** [comment]
OK. Not sure how I can do this in this pull request. Should I make a new one?
I think the same issue is in another pull request I made.

**Comment by yahonda** [comment]
Pull requests are created to merge your branch into the upstream branch (rsim/oracle-enhanced/rails42).

Now https://github.com/swisslife-select/oracle-enhanced/commit/232ec82676e7fca5d03b3246e5235cef74adb87c and https://github.com/swisslife-select/oracle-enhanced/commit/c2cde1ba73a4160b21971bb4d8d6d6e97ba71d3c have been merged to rails42 branch. Then just rebase your branch (swisslife-select:rails42-GIH545) and `git push -f <your branch>` should work.

i.e.
```ruby
git checkout rails42
git fetch upstream (or remote branch name which points rsim/oracle-enhanced.git)
git merge upstream/rails42
git checkout swisslife-select:rails42-GIH545
git rebase rails42
git push -f origin swisslife-select:rails42-GIH545
```

please give it a try. if it works no need to open another pull request.

**Comment by apeiros** [comment]
Ah, ok. I generally don't use rebase on "published" branches as it can cause serious issues. Will do it here. Thank you for the detailed description!

**Comment by yahonda** [comment]
Merged. It looks git can handle duplicate commits correctly

**Pull request merged**
