### PR TITLE
Move spec files under `oracle_enhanced` directory

### PR DESCRIPTION
**Pull request by yahonda**
This pull request moves spec files under `oracle_enhanced` directory.
#584 introduced `OracleEnhanced` module and created sub directory for modules. It did not touch specs.

### CODE REVIEW

**Comment by yahonda** [comment]
@koic Would you review and give honest feedback. I like this module structure but I do not know if it is kind of rspec way or something like that.

**Comment by koic** [comment]
I often see a directory layout `spec/**/*_ spec.rb` against `lib/**/*.rb`. And I think that this testing pair is easy to understand.

However, there are points that I care about with this change. That is that not everything can be applied to that directory layout.

The following changes are good changes as there is a file pairing in the `lib` directory.

- oracle_enhanced_connection_spec.rb → oracle_enhanced/connection_spec.rb
- oracle_enhanced_context_index_spec.rb → oracle_enhanced/context_index_spec.rb
- oracle_enhanced_database_tasks_spec.rb → oracle_enhanced/database_tasks_spec.rb
- oracle_enhanced_procedures_spec.rb → oracle_enhanced/procedures_spec.rb
- oracle_enhanced_schema_statements_spec.rb → oracle_enhanced/schema_statements_spec.rb
- oracle_enhanced_structure_dump_spec.rb → oracle_enhanced/structure_dump_spec.rb

On the other hand, the following changes do not exist a file that is paired in the `lib` directory. Therefore it is difficult whether this change is good or not...

- oracle_enhanced_data_types_spec.rb → oracle_enhanced/data_types_spec.rb
- oracle_enhanced_dirty_spec.rb → oracle_enhanced/dirty_spec.rb
- oracle_enhanced_dbms_output_spec.rb → oracle_enhanced/dbms_output_spec.rb
- oracle_enhanced_emulate_oracle_adapter_spec.rb → oracle_enhanced/emulate_oracle_adapter_spec.rb
- oracle_enhanced_schema_dump_spec.rb → oracle_enhanced/schema_dump_spec.rb

**Comment by yahonda** [comment]
Thanks for the review. Updated this pull request to move spec files under oracle_enhanced only if the corresponding files exist under lib.

**Comment by koic** [comment]
Thanks for the update. Let's look at the remaining spec files later.

**Comment by yahonda** [comment]
Thanks for merging and opening two follow up pull requests.

**Pull request merged**
