### PR TITLE
Deprecate `supports_statement_cache?`

### PR DESCRIPTION
**Pull request by koic**
Follow up to rails/rails#28938.

### CODE REVIEW

**Comment by koic** [comment]
@yahonda After passing Travis CI build, should I open a PR that backporting this commit to `nextval` branch?

**Comment by koic** [comment]
Or is backporting unnecessary? There is a solution such as `rebase master` on ` nextval` branch.

(About the function/branch of the future, the phrase "backporting" was strange.)

**Comment by yahonda** [comment]
Thanks for your work and good question.

The short answer is no. Since `nextval` is a kind of topic branch (feature branch) which will be merged to master at some future, unlike other `release18` branches. 

In the meantime, I'll merge master branches into nextval branch periodically.

**Comment by yahonda** [comment]
I have merged master branch into nextval. c29bf316d7a864f3511c6f22b2d654f95c16c0f9 . Going foward merge operation will be done without issues/pull requests.

**Comment by koic** [comment]
Thanks for your reply. I understood the policy of development on `nextval` branch.

**Pull request merged**
