### PR TITLE
Fix keyword arguments errors for Ruby 2.8.0-dev

### PR DESCRIPTION
**Pull request by koic**
This PR fixes the following keyword arguments errors for Ruby 2.8.0-dev.
https://travis-ci.org/rsim/oracle-enhanced/jobs/633096860

### CODE REVIEW

**Comment by koic** [comment]
`$ ruby guides/bug_report_templates/active_record_gem.rb` command of ruby-head matrix has been failed.
https://travis-ci.org/rsim/oracle-enhanced/jobs/633110654#L520

```console
$ ruby guides/bug_report_templates/active_record_gem.rb
(snip)

Using activerecord-oracle_enhanced-adapter 6.1.0.alpha from https://github.com/rsim/oracle-enhanced.git (at master@07a25e8)
Using bundler 2.1.2
Fetching method_source 0.9.2
Installing method_source 0.9.2
Fetching thor 1.0.1
Installing thor 1.0.1
Using railties 6.1.0.alpha from https://github.com/rails/rails.git (at master@f619ac9)
Fetching sprockets 4.0.0
Installing sprockets 4.0.0
Fetching sprockets-rails 3.2.1
Installing sprockets-rails 3.2.1
Using rails 6.1.0.alpha from https://github.com/rails/rails.git (at master@f619ac9)
Fetching ruby-oci8 2.2.7
Installing ruby-oci8 2.2.7 with native extensions
-- create_table(:posts, {:force=>true})
Traceback (most recent call last):
	13: from guides/bug_report_templates/active_record_gem.rb:45:in `<main>'
	12: from /home/travis/.rvm/gems/ruby-head/bundler/gems/rails-f619ac91d33b/activerecord/lib/active_record/schema.rb:46:in `define'
	11: from /home/travis/.rvm/gems/ruby-head/bundler/gems/rails-f619ac91d33b/activerecord/lib/active_record/schema.rb:50:in `define'
	10: from /home/travis/.rvm/gems/ruby-head/bundler/gems/rails-f619ac91d33b/activerecord/lib/active_record/schema.rb:50:in `instance_eval'
	 9: from guides/bug_report_templates/active_record_gem.rb:46:in `block in <main>'
	 8: from /home/travis/.rvm/gems/ruby-head/bundler/gems/rails-f619ac91d33b/activerecord/lib/active_record/migration.rb:895:in `method_missing'
	 7: from /home/travis/.rvm/gems/ruby-head/bundler/gems/rails-f619ac91d33b/activerecord/lib/active_record/migration.rb:874:in `say_with_time'
	 6: from /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.8.0/benchmark.rb:293:in `measure'
	 5: from /home/travis/.rvm/gems/ruby-head/bundler/gems/rails-f619ac91d33b/activerecord/lib/active_record/migration.rb:874:in `block in say_with_time'
	 4: from /home/travis/.rvm/gems/ruby-head/bundler/gems/rails-f619ac91d33b/activerecord/lib/active_record/migration.rb:910:in `block in method_missing'
	 3: from /home/travis/.rvm/gems/ruby-head/bundler/gems/oracle-enhanced-07a25e82a926/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:201:in `create_table'
	 2: from /home/travis/.rvm/gems/ruby-head/bundler/gems/oracle-enhanced-07a25e82a926/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:628:in `create_table_definition'
	 1: from /home/travis/.rvm/gems/ruby-head/bundler/gems/oracle-enhanced-07a25e82a926/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:628:in `new'
/home/travis/.rvm/gems/ruby-head/bundler/gems/oracle-enhanced-07a25e82a926/lib/active_record/connection_adapters/oracle_enhanced/schema_definitions.rb:56:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
The command "ruby guides/bug_report_templates/active_record_gem.rb" exited with 1.
```

[activerecord-oracle_enhanced-adapter is specified using `github: "rsim/oracle-enhanced"` option](https://github.com/rsim/oracle-enhanced/blob/master/guides/bug_report_templates/active_record_gem.rb#L11), but activerecord-oracle_enhanced-adapter on GitHub does not include this PR change yet.

I think this error will be resolved by merging this PR.

**Comment by koic** [comment]
Thanks!

**Comment by koic** [comment]
By the way, Rails seems to be working on backporting kwargs separation to 6.0 stable.
https://github.com/rails/rails/pull/37935

Will the Oracle enhanced adapter also backport to 6.0 stable?
https://github.com/rsim/oracle-enhanced/commits/release60

Rails 6.1 release plans is out of sight. So IMHO, backporting to 6.0 stable is useful for real world applications using Ruby 2.7 or later.

**Comment by yahonda** [comment]
Let’s backport this and future pull requests to support new keyword arguments support for release60.
I mean you can backport them by yourself.

For release52 and older branch, let's remove CI against ruby-head.

**Comment by koic** [comment]
Thank you for your answer. After Rails backport settles down, I'll try to work on it.

**Pull request merged**
