### PR TITLE
Rails 6.2 is now Rails 7.0

### PR DESCRIPTION
**Pull request by koic**
Follow https://github.com/rails/rails/commit/1b455e2e9d6937d4107e19cb32e2f98aa08886b9.

### CODE REVIEW

**Comment by koic** [comment]
I will apply https://github.com/rails/rails/commit/6487836af8f50648a9b30ce61864c827132e5592 to this PR and investigate failure spec ASAP.

**Comment by yahonda** [comment]
It looks like JRuby 9.4 is planned to support Ruby 2.7. Then in the meantime, we may need to disable CI against all of the JRuby versions.

https://github.com/jruby/jruby/issues/6464

**Comment by koic** [comment]
Thanks for the information. I disabled JRuby CI matrix.

**Comment by koic** [comment]
MRI 2.7 and MRI 3.0 build errors are not related to Rails 7.0. They will be resolved in #2138.

**Comment by yahonda** [comment]
CI failures happen at bug report templates, which needs this pull request merged anyway.

**Comment by koic** [comment]
The master build branch has been successful! Thank you!
https://github.com/rsim/oracle-enhanced/runs/1837493794

**Pull request merged**
